"""
Topic task pool — storage and state tracking for per-topic task pools.

Pools are generated by daily_tasks._generate_pool() on first use and stored at
{slug}/topic_pool_{topic_id}.json.
"""
from __future__ import annotations

import json
from typing import Any, Dict, List, Optional

from . import module_profile as mp


def _slug_for(module_name: str) -> str:
    profile = mp.load(module_name)
    return profile["slug"] if profile else mp._slugify(module_name)


def _pool_path(module_name: str, topic_id: str) -> str:
    return f"{_slug_for(module_name)}/topic_pool_{topic_id}.json"


def load_pool(module_name: str, topic_id: str) -> Optional[Dict[str, Any]]:
    from app.storage import storage_backend as sb
    raw = sb.read_text(_pool_path(module_name, topic_id))
    if not raw:
        return None
    try:
        return json.loads(raw)
    except Exception:
        return None


def save_pool(module_name: str, topic_id: str, pool: Dict[str, Any]) -> None:
    from app.storage import storage_backend as sb
    sb.write_text(
        _pool_path(module_name, topic_id),
        json.dumps(pool, ensure_ascii=False, indent=2),
    )


def delete_pool(module_name: str, topic_id: str) -> bool:
    from app.storage import storage_backend as sb
    return sb.delete(_pool_path(module_name, topic_id))


def get_next_tasks(module_name: str, topic_id: str, n: int) -> List[Dict[str, Any]]:
    """Return the next ``n`` open (not done) tasks from the pool as fresh entries."""
    pool = load_pool(module_name, topic_id)
    if not pool:
        return []
    open_tasks = [t for t in (pool.get("tasks") or []) if not t.get("done")]
    return [{"text": t["text"], "done": False} for t in open_tasks[:n]]


def mark_task_done(module_name: str, topic_id: str, task_text: str) -> None:
    """Mark the first matching open task done in the pool and persist."""
    pool = load_pool(module_name, topic_id)
    if not pool:
        return
    for t in pool.get("tasks") or []:
        if t.get("text") == task_text and not t.get("done"):
            t["done"] = True
            save_pool(module_name, topic_id, pool)
            return


def unmark_task(module_name: str, topic_id: str, task_text: str) -> None:
    """Re-open a pool task (used when the user un-checks it in the daily plan)."""
    pool = load_pool(module_name, topic_id)
    if not pool:
        return
    for t in pool.get("tasks") or []:
        if t.get("text") == task_text and t.get("done"):
            t["done"] = False
            save_pool(module_name, topic_id, pool)
            return


def is_pool_complete(module_name: str, topic_id: str) -> bool:
    """True only if the pool exists, has tasks, and every task is done."""
    pool = load_pool(module_name, topic_id)
    tasks = (pool.get("tasks") if pool else None) or []
    if not tasks:
        return False
    return all(t.get("done") for t in tasks)


def pool_progress(module_name: str, topic_id: str) -> Dict[str, int]:
    """Return {"done": int, "total": int} for the topic's pool."""
    pool = load_pool(module_name, topic_id)
    tasks = (pool.get("tasks") if pool else None) or []
    done = sum(1 for t in tasks if t.get("done"))
    return {"done": done, "total": len(tasks)}
