"""
Topic task pool — storage and state tracking for per-topic task pools.

Pools are generated by daily_tasks._generate_pool() on first use and stored at
{slug}/topic_pool_{topic_id}.json.
"""
from __future__ import annotations

import json
from typing import Any, Dict, List, Optional

from . import module_profile as mp


def _slug_for(module_name: str) -> str:
    profile = mp.load(module_name)
    return profile["slug"] if profile else mp._slugify(module_name)


def _pool_path(module_name: str, topic_id: str) -> str:
    return f"{_slug_for(module_name)}/topic_pool_{topic_id}.json"


def load_pool(module_name: str, topic_id: str) -> Optional[Dict[str, Any]]:
    from app.storage import storage_backend as sb
    raw = sb.read_text(_pool_path(module_name, topic_id))
    if not raw:
        return None
    try:
        return json.loads(raw)
    except Exception:
        return None


def save_pool(module_name: str, topic_id: str, pool: Dict[str, Any]) -> None:
    from app.storage import storage_backend as sb
    sb.write_text(
        _pool_path(module_name, topic_id),
        json.dumps(pool, ensure_ascii=False, indent=2),
    )


def delete_pool(module_name: str, topic_id: str) -> bool:
    from app.storage import storage_backend as sb
    return sb.delete(_pool_path(module_name, topic_id))


def get_next_tasks(module_name: str, topic_id: str, n: int) -> List[Dict[str, Any]]:
    """Return the next ``n`` open (not done) tasks from the pool as fresh entries."""
    pool = load_pool(module_name, topic_id)
    if not pool:
        return []
    open_tasks = [t for t in (pool.get("tasks") or []) if not t.get("done")]
    return [{"text": t["text"], "done": False, "minutes": t.get("minutes", 45)} for t in open_tasks[:n]]


def get_tasks_for_hours(module_name: str, topic_id: str, hours: float) -> List[Dict[str, Any]]:
    """Return open tasks from the pool until the time budget (in hours) is used up.

    Always returns at least one task. Stops before adding a task that would
    exceed the budget, unless the result would otherwise be empty.
    """
    pool = load_pool(module_name, topic_id)
    if not pool:
        return []
    budget_min = hours * 60
    open_tasks = [t for t in (pool.get("tasks") or []) if not t.get("done")]
    result: List[Dict[str, Any]] = []
    used = 0
    for t in open_tasks:
        task_min = t.get("minutes", 45)
        if result and used + task_min > budget_min:
            break
        result.append({"text": t["text"], "done": False, "minutes": task_min})
        used += task_min
    return result


def mark_task_done(module_name: str, topic_id: str, task_text: str) -> None:
    """Mark the first matching open task done in the pool and persist."""
    pool = load_pool(module_name, topic_id)
    if not pool:
        return
    for t in pool.get("tasks") or []:
        if t.get("text") == task_text and not t.get("done"):
            t["done"] = True
            save_pool(module_name, topic_id, pool)
            return


def unmark_task(module_name: str, topic_id: str, task_text: str) -> None:
    """Re-open a pool task (used when the user un-checks it in the daily plan)."""
    pool = load_pool(module_name, topic_id)
    if not pool:
        return
    for t in pool.get("tasks") or []:
        if t.get("text") == task_text and t.get("done"):
            t["done"] = False
            save_pool(module_name, topic_id, pool)
            return


def is_pool_complete(module_name: str, topic_id: str) -> bool:
    """True only if the pool exists, has tasks, and every task is done."""
    pool = load_pool(module_name, topic_id)
    tasks = (pool.get("tasks") if pool else None) or []
    if not tasks:
        return False
    return all(t.get("done") for t in tasks)


def pool_progress(module_name: str, topic_id: str) -> Dict[str, int]:
    """Return {"done": int, "total": int} for the topic's pool."""
    pool = load_pool(module_name, topic_id)
    tasks = (pool.get("tasks") if pool else None) or []
    done = sum(1 for t in tasks if t.get("done"))
    return {"done": done, "total": len(tasks)}


def delete_all_pools(module_name: str) -> int:
    """Delete all topic pools for a module. Returns count of deleted pools."""
    from app.storage import storage_backend as sb
    from app.storage.supabase_client import get_client, get_user_id
    slug = _slug_for(module_name)
    uid = get_user_id()
    # list() returns immediate children of the slug folder, not the user root
    folder = f"{uid}/{slug}"
    deleted = 0
    try:
        items = get_client().storage.from_(sb.BUCKET).list(folder)
        for item in (items or []):
            name = item.get("name", "")
            if name.startswith("topic_pool_") and name.endswith(".json"):
                if sb.delete(f"{slug}/{name}"):
                    deleted += 1
    except Exception as exc:
        import logging
        logging.getLogger(__name__).warning("delete_all_pools list failed for %s: %s", slug, exc)
    return deleted
